// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Template.Data.Context;

namespace Movements.Data.Migrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20220207164414_changing-data")]
    partial class changingdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Movements.Domain.Entities.Cosif", b =>
                {
                    b.Property<string>("CodCosif")
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength(true);

                    b.Property<string>("CodClassification")
                        .HasMaxLength(6)
                        .HasColumnType("nchar(6)")
                        .IsFixedLength(true);

                    b.Property<string>("CodProduct")
                        .HasColumnType("nchar(4)");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength(true);

                    b.HasKey("CodCosif");

                    b.HasIndex("CodProduct");

                    b.ToTable("PRODUCT_COSIF");

                    b.HasData(
                        new
                        {
                            CodCosif = "00000000001",
                            CodClassification = "000001",
                            Status = "A"
                        },
                        new
                        {
                            CodCosif = "00000000002",
                            CodClassification = "000002",
                            Status = "I"
                        },
                        new
                        {
                            CodCosif = "00000000003",
                            CodClassification = "000003",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("Movements.Domain.Entities.Movement", b =>
                {
                    b.Property<int>("EntryNumber")
                        .HasMaxLength(18)
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.Property<int>("Month")
                        .HasMaxLength(2)
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.Property<int>("Year")
                        .HasMaxLength(4)
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.Property<string>("CodCosif")
                        .HasMaxLength(11)
                        .HasColumnType("nchar(11)")
                        .IsFixedLength(true);

                    b.Property<string>("CodProduct")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength(true);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength(true);

                    b.Property<DateTime>("MovimentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nchar(15)")
                        .IsFixedLength(true);

                    b.Property<int>("Value")
                        .HasMaxLength(18)
                        .HasColumnType("int")
                        .IsFixedLength(true);

                    b.HasKey("EntryNumber", "Month", "Year");

                    b.ToTable("MANUAL_MOVIMENTS");
                });

            modelBuilder.Entity("Movements.Domain.Entities.Product", b =>
                {
                    b.Property<string>("CodProduct")
                        .HasMaxLength(4)
                        .HasColumnType("nchar(4)")
                        .IsFixedLength(true);

                    b.Property<string>("Description")
                        .HasMaxLength(30)
                        .HasColumnType("nchar(30)")
                        .IsFixedLength(true);

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .HasColumnType("nchar(1)")
                        .IsFixedLength(true);

                    b.HasKey("CodProduct");

                    b.ToTable("PRODUCT");

                    b.HasData(
                        new
                        {
                            CodProduct = "0001",
                            Description = "Notebook",
                            Status = "A"
                        },
                        new
                        {
                            CodProduct = "0002",
                            Description = "Book",
                            Status = "I"
                        },
                        new
                        {
                            CodProduct = "0003",
                            Description = "Head Phone",
                            Status = "A"
                        });
                });

            modelBuilder.Entity("Movements.Domain.Entities.Cosif", b =>
                {
                    b.HasOne("Movements.Domain.Entities.Product", "Product")
                        .WithMany("Cosif")
                        .HasForeignKey("CodProduct");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Movements.Domain.Entities.Product", b =>
                {
                    b.Navigation("Cosif");
                });
#pragma warning restore 612, 618
        }
    }
}
